### PR TITLE
Update to 0.9.6

### PR DESCRIPTION
**Pull request by pp-r**
## Problem

- *A new version is out fixing various XSS issues and a possible SQL injection | https://doc.galette.eu/en/master/changelog.html#v0960*

## Solution

- *Update to 0.9.6*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by pp-r** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by pp-r** [comment]
Hello,

I'm not familiar with GitHub so is there a way to edit this PR (app source, manifest, readme and readme_fr) -or had to wait before push another one- because of this https://galette.eu/site/fr/post/2021/12/16/galette-0-9-6-1.html ?
https://download.tuxfamily.org/galette/galette-0.9.6.1.tar.bz2
7f3d09af19711372cc35d48352e115ee96e835ea879298347289d274308bb011

ppr

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
testme!

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
still the same error `GALETTE_TPL_SUBDIR` I assume, it comes from upstream app, maybe we should wait for next version

**Pull request closed without merging**
