### PR TITLE
Update upstream version 0.9.6.1 and php 7.4

### PR DESCRIPTION
**Pull request by pp-r**
## Problem

- *A new version is out*

## Solution

- *Update upstream version 0.9.6.1 and use php 7.4*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by pp-r** [comment]
!testme

**Comment by pp-r** [comment]
!testme

**Comment by pp-r** [comment]
!testme

**Comment by pp-r** [comment]
!testme

**Comment by pp-r** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
