### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Comment by alexAubin** [comment]
`"PHP message: PHP Fatal error:  Uncaught ErrorException: Use of undefined constant GALETTE_TPL_SUBDIR - assumed 'GALETTE_TPL_SUBDIR' (this will throw an Error in a future version of PHP) in /var/www/galette/galette/includes/dependencies.php:71`

:thinking:

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
